config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  devise_for :admins
  devise_for :students
  devise_for :teachers

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "home#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")

  resources :departments
  resources :semesters
  resources :subjects
  resources :students

  namespace :api do
    get :subjects, to: "subjects#index"
    get :students, to: "students#index"
    get :students_with_attendance, to: "students#with_attendance"
    get :attendances, to: "attendances#index"
    get :existing_attendance, to: "attendances#existing_attendance"
    get :'attendance/summary', to: 'api#attendance_summary'
  end

  resources :attendances, only: [] do
    collection do
      get :bulk_show
      get :bulk_new
      get :bulk_view
      post :bulk_create
    end
  end

  #Admins
  resources :admins,only: [:index,:show, :new, :create, :edit, :update, :destroy]
  # Students
  resources :students, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  # Teachers
  resources :teachers, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  # Departments
  resources :departments, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  # Semesters
  resources :semesters, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  # Subjects
  resources :subjects, only: [:index, :show, :new, :create, :edit, :update, :destroy]
end

app/views/shared/_flash_messages.html.erb
<%
  alert_type = {
    alert: :warning,
    notice: :success
  }
%>
<% flash.each do |type, msg| %>
  <div class="mt-2 alert alert-<%= alert_type[type.to_sym] %>">
    <%= msg %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Remove the container if you want to extend the Footer to full width. -->
<div class="container-fluid">

  <footer class="text-center text-white" style="background-color: #f1f1f1;">
  <!-- Grid container -->
  <div class="container pt-4">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-linkedin"></i
      ></a>
      <!-- Github -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2025 Copyright:
    <a class="text-dark" href="#">teamsangramjit.com</a>
  </div>
  <!-- Copyright -->
</footer>

</div>
<!-- End of .container -->

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">AMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", "/", class: "nav-link active", 'aria-current': :page %>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Authentication
          </a>
          <ul class="dropdown-menu p-2" aria-labelledby="navbarDropdown">

            <% if teacher_signed_in? %>
              <li><%= current_teacher.email %></li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <%= button_to "Sign Out", destroy_teacher_session_path, class: 'dropdown-item', method: :delete %>
              </li>
            <% elsif admin_signed_in? %>
              <li><%= current_admin&.email %></li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <%= button_to "Sign Out", destroy_admin_session_path, class: 'dropdown-item', method: :delete %>
              </li>
            <% elsif student_signed_in? %>
              <li><%= current_student.email %></li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <%= button_to "Sign Out", destroy_teacher_session_path, class: 'dropdown-item', method: :delete %>
              </li>
            <% else %>
              <li><%= link_to "Admin Sign In", new_admin_session_path, class: 'dropdown-item' %><li>
              <li><%= link_to "Teacher Sign In", new_teacher_session_path, class: 'dropdown-item' %><li>
              <li><%= link_to "Student Sign In", new_student_session_path, class: 'dropdown-item' %><li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>