config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  devise_for :admins
  devise_for :students
  devise_for :teachers

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "home#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")

  resources :departments
  resources :semesters
  resources :subjects
  resources :students

  namespace :api do
    get :subjects, to: "subjects#index"
    get :students, to: "students#index"
    get :students_with_attendance, to: "students#with_attendance"
    get :attendances, to: "attendances#index"
    get :existing_attendance, to: "attendances#existing_attendance"
    get :'attendance/summary', to: 'api#attendance_summary'
  end

  resources :attendances, only: [] do
    collection do
      get :bulk_show
      get :bulk_new
      get :bulk_view
      post :bulk_create
    end
  end

  #Admins
  resources :admins,only: [:index,:show, :new, :create, :edit, :update, :destroy]
  # Students
  resources :students, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  # Teachers
  resources :teachers, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  # Departments
  resources :departments, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  # Semesters
  resources :semesters, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  # Subjects
  resources :subjects, only: [:index, :show, :new, :create, :edit, :update, :destroy]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/home/index.html.erb
<% if teacher_signed_in? %>
  <h1>Welcome teacher <%= current_teacher.name %></h1>
<% elsif student_signed_in? %>
  <h1>Welcome student <%= current_student.name %></h1>
<% elsif admin_signed_in? %>
  <h1>Welcome administrator <%= current_admin.email%></h1>
<% else %>
<h1>Welcome to the home page</h1>
<% end %>
<br>
<br>
<br>



<% if teacher_signed_in? %>
  <%= link_to "New Attendance", bulk_new_attendances_path, class: "btn btn-danger", data: { turbo: false } %>
  <br>
  <%= link_to "View Attendance",bulk_view_attendances_path,class:"btn btn-primary mt-2",data:{turbo:false} %>
  <br>
<% end %>



<% if admin_signed_in? %>
  <%= link_to "Departments", departments_path, class: "btn btn-primary mt-2", data: { turbo: false }%>
  <br>
  <%= link_to "Semesters", semesters_path, class: "btn btn-primary mt-2",data: { turbo: false } %>
  <br>
  <%= link_to "Subjects", subjects_path, class: "btn btn-primary mt-2",data: { turbo: false } %>
  <br>
  <%= link_to "Students", students_path, class: "btn btn-primary mt-2",data: { turbo: false } %>
  <br>
  <%= link_to "Teachers",teachers_path, class: "btn btn-primary mt-2",data: { turbo: false } %>
  <br>
<% end %>

<% if student_signed_in? %>
  <%= link_to "My Attendance", bulk_show_attendances_path, class: "btn btn-primary mt-2", data: { turbo: false } %>
<% end %>